# Generated by Django 4.1.2 on 2022-10-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="emial",
            new_name="email",
        ),
    ]
